### ISSUE TITLE
Link to non-existent service

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#1]
In sec_oss_build_portfolio.html link to [Wikispaces](http://www.wikispaces.com/) is broken because Wikispace doesn't exist.
![image](https://github.com/pearcej/opensource/assets/117699634/c229e5fa-caf0-4c06-9965-ea26d7e48b5a)

**Comment by pearcej** [comment]
@demekenega can you locate an appropriate alternative?

**Comment by pearcej** [comment]
@demekenega Nevermind. I found one.
