### ISSUE TITLE
404 errors in multiple links

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#11]
In sec_licensing_existing_communities.html all highlighted links give a 404 error.
![image](https://github.com/pearcej/opensource/assets/117699634/6e615744-dfbf-4992-983f-87b8e005275a)

**Comment by thaopham03** [comment]
For the MIT license and ISC license, I am not sure which website to choose (because there are so many of them), so I would pick their Wikipedia pages due to their inclusiveness.

**Comment by demekenega** [comment]
@thaopham03 's fix fixes this issue, but she also tries to fix #13 in the same branch.

**Comment by thaopham03** [comment]
@demekenega Thank you Nega, I have deleted issue13 branch from this branch. Thank you for the comment! I will go ahead and create a pull request for this issue.
