### ISSUE TITLE
Duplicated index

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#118]
In index-1.html, indexed the word intellectual property twice on the index page. The first index is intellectual property, and the second is IP which is the attribution of intellectual property. 

We don't need to index the word intellectual property (IP) twice; instead, we can have one index for intellectual property / IP.

![image](https://github.com/pearcej/opensource/assets/117699634/b8369abc-7c4b-4bf1-a59d-f777352377b0)

**Comment by pearcej** [comment]
I think this is fine since a person might look up one but not the other.
