### ISSUE TITLE
Prerequisite issue

### ISSUE THREAD

**Issue by thaopham03** [pearcej/opensource#12]
As discussed in the meeting, there are some exercises in Chapter 1 that require readers to have a coding background (C++). We need to discuss how should we write a prerequisite page for readers because Dr. Pearce intended to publish this book for everyone.

Location: sec_oss_source_code.html

**Comment by demekenega** [comment]
@thaopham03 's fix has no change.

**Comment by thaopham03** [comment]
I have fixed the issue. I will create a pull request for this issue now.
