### ISSUE TITLE
Missing a hyphen

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#14]
In 4.2 Basic Shell Commands (sec_dev_basic_shell_commands.html), the word case-sensitive doesn't have a hyphen.
![image](https://github.com/pearcej/opensource/assets/117699634/8cf2cb1f-160f-4738-a136-a6faad2f30a0)

**Comment by demekenega** [comment]
@thaopham03  's fix only changes one of the words, but there are three words.

**Comment by pearcej** [comment]
Strange as it seems, hyphenation of compound word phrases like "case sensitive" is complicated. See https://www.merriam-webster.com/words-at-play/hyphen-rules-open-closed-compound-words.  When used as a noun, it is not hyphenated.  

 The commit 9c329db fixes this issue.
