### ISSUE TITLE
Incorrect capitalization 

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#15]
In the 4.3 We All Need an Editor(sec_dev_editors.html) section, the word Microsoft Word capitalize incorrectly "W' in words should be capitalized.
![image](https://github.com/pearcej/opensource/assets/117699634/f29c6568-1da9-467f-bd68-3fe20bcbdeb1)

**Comment by thaopham03** [comment]
The issue was already resolved. Close issue for now.

**Comment by demekenega** [comment]
@thaopham03 's fix seems good.
