### ISSUE TITLE
Missing a period

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#18]
In 5.2 Getting Started with Git(sec_git_getting_started.html) the part that talks about the history of Git it misses a period in the end.
![image](https://github.com/pearcej/opensource/assets/117699634/8adbd28f-4f90-4b4c-ba0f-54e1f585747e)

**Comment by eygul** [comment]
@demekenega 's fix did not solve the problem.

**Comment by pearcej** [comment]
@demekenega Do you want to try again?

**Comment by demekenega** [comment]
@eygul @pearcej successfully resolve the issue. check #57
