### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#19]
In chapter five (sec_git_branching.html), Figure 5.4.8 is not showing.
![image](https://github.com/pearcej/opensource/assets/117699634/4992c6be-f56d-4e9a-8276-2281b2761e43)

**Comment by demekenega** [comment]
Also, Figure 5.4.9 have the same problem.
![image](https://github.com/pearcej/opensource/assets/117699634/607da4b1-fc6a-4ebb-a847-2c166b255202)

**Comment by pearcej** [comment]
Fixed with commit 2933fecd140931adb80e86c2c238e8d253f107c1
