### ISSUE TITLE
Dual Boot Option For Older Windows Machines 

### ISSUE THREAD

**Issue by eygul** [pearcej/opensource#204]
In Section 4.1 (sec_dev_shell.html), different ways of setting up a development environment were mentioned. For computers that utilize an older Windows version, Virtual Machines are suggested in the book. Given that the computers with older Windows versions are also generally older-technology machines with less computing power, Virtual Machines may be too slow for them considering Virtual Machines require a lot of processing power. That is why for older Windows computers, I suggest adding dual boot with Linux as a recommended option in the book. It requires a lot less processing power and users can have a full Linux operating system available to them.

**Comment by pearcej** [comment]
@eygul I welcome a pull request on this. Please be sure it is short and modern!
