### ISSUE TITLE
Missing int return type section 1.3.1

### ISSUE THREAD

**Issue by njounkengdaizem** [pearcej/opensource#205]
**1.3.1 What is Source Sode**

 Missing an 'int' return type could mean defaulting to int. 
 The error however seems to require explicit return types for functions 

**Fix**
- [ ] Replace `main() ` with `int main()`

<img width="300" alt="Screenshot 2023-08-24 at 11 32 31 AM" src="https://github.com/pearcej/opensource/assets/89226977/ccf18e49-5b14-4f67-b026-5da73f93a409">

**Comment by pearcej** [comment]
fixed by cdfdf7cf55b7f82d4dfa5c40ea1c7ae1b233ac57
