### ISSUE TITLE
Wrong tag usage

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#208]
In sec_dev_basic_shell_commands.ptx for Output redirection symbol used `<c>` tag, which causes errors in multiple lines.

to solve that we should use -> `< m >& g t; `tag.![image](https://github.com/pearcej/opensource/assets/117699634/856afb29-ce3a-4b03-be8b-5a9d13893f59)

**Comment by pearcej** [comment]
These seem to render in the book correctly. I am not sure we should change it.
