### ISSUE TITLE
Grammatical error and duplicated word

### ISSUE THREAD

**Issue by thaopham03** [pearcej/opensource#23]
4.1.3 Accessing a Terminal Window on your Machine (location: sec_dev_shell_terms.html): there should be a space between the comma and “including”. Also, the word “find” is duplicated.
![image](https://github.com/pearcej/opensource/assets/118550787/b86fbb9a-8542-436d-8efb-f82dab74d9a8)

**Comment by eygul** [comment]
@demekenega 's fix seems to be good.
