### ISSUE TITLE
Weird sentence structure

### ISSUE THREAD

**Issue by thaopham03** [pearcej/opensource#27]
5.1 Why Version Control? (git-why-version-control.html)
I don't this sentence make sense, it should be "You re-read it yourself, then create a new edited version" as my suggestion. 
![image](https://github.com/pearcej/opensource/assets/118550787/7ec0d2a9-9217-4cda-9e0d-c723f939199c)

**Comment by eygul** [comment]
@demekenega 's fix seems to be good.
