### ISSUE TITLE
None existing link

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#29]
In 5.6 (sec_git_github.html), multiple links have a 404 error and one nonexistent link.  
![image](https://github.com/pearcej/opensource/assets/117699634/d8df97e7-7f81-459d-b4f8-5967143506f9)
![image](https://github.com/pearcej/opensource/assets/117699634/8d8dcf0d-8989-4336-ac52-c7d55dc03157)
![image](https://github.com/pearcej/opensource/assets/117699634/7465214d-5cb1-427e-8528-be18d9f8688b)
![image](https://github.com/pearcej/opensource/assets/117699634/4ec3e573-c03b-40c4-a5e6-bdd86d44a652)
![image](https://github.com/pearcej/opensource/assets/117699634/47cd8d79-2589-42ef-8e25-72626528c9b8)
![image](https://github.com/pearcej/opensource/assets/117699634/96e4e766-d0b3-4e60-9454-d88e1854df9d)
![image](https://github.com/pearcej/opensource/assets/117699634/581da7c4-590b-4155-96a1-b1e1ece731fc)

**Comment by pearcej** [comment]
@demekenega please break this issue into multiple issues with one for each problem and with more descriptive titles.

**Comment by pearcej** [comment]
@demekenega Can you please review again?

**Comment by pearcej** [comment]
@demekenega have you had a chance to re-review?

**Comment by pearcej** [comment]
@demekenega Thanks for the excellent review in our Slack channel.  I am glad all the problems have been corrected.
