### ISSUE TITLE
 Nonexistent images

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#30]
In 5.4 (sec_git_branching.html), there are two none existent images.
![image](https://github.com/pearcej/opensource/assets/117699634/37244f14-f68e-4d2b-a1a5-c5aecce279fd)
![image](https://github.com/pearcej/opensource/assets/117699634/bc0aa310-4763-4e5c-b7f5-dd641d99f63b)

**Comment by pearcej** [comment]
the commit2933fecd140931adb80e86c2c238e8d253f107c1 resolves this issue
