### ISSUE TITLE
Add git fetch to index

### ISSUE THREAD

**Issue by IsaacSGray** [pearcej/opensource#300]
git fetch is not in the index. 

git p tags are ignored and paragraph takes priority, indexing the entire section. 

I will be adding the entire section to the index until this is fixed.

**Comment by IsaacSGray** [comment]
Added an extra line, git fetch has no mention where it is explained, it is deeply embedded in other tags in the heading.

**Comment by pearcej** [comment]
Since this replaces #274, you should have just edited that issue.
