### ISSUE TITLE
Typo in section 6.2.1

### ISSUE THREAD

**Issue by andersoncedu** [pearcej/opensource#301]
There's a sentence, number 1 in the list under the first paragraph in section 6.2.1 which reads: 

Developers often don’t like technical writing **for** think that writing is not a principal skill.

This is a typo an needs to be addressed.

**Comment by pearcej** [comment]
@andersoncedu Thanks! Pull-request welcome!

**Comment by andersoncedu** [comment]
Okay, I'm working on this!
