### ISSUE TITLE
Expand list of "Friendly Projects"

### ISSUE THREAD

**Issue by emmet0r** [pearcej/opensource#309]
A few suggestions based on my own anecdotal experiences:

* p5.js ([website](https://p5js.org) | [GitHub](https://github.com/processing/p5.js)) - _creative coding_
* CHAOSS ([website](https://chaoss.community) | [GitHub](https://github.com/chaoss)) - _community health_
* OpenSSF ([website](https://openssf.org) | [GitHub](https://github.com/ossf)) - _security_

CHAOSS & OpenSSF are communities that oversee multiple projects. Would it make sense to change the title of this section to "Friendly Communities"? Or maybe list these in a separate subsection to highlight this distinction?

**Comment by pearcej** [comment]
@emmet0r Sure! I would welcome a pull-request on this.

**Comment by pearcej** [comment]
@emmet0r I love this - any chance you can give me a pull-request?

**Comment by emmet0r** [comment]
@pearcej Finally catching up on some loose ends - will work on this this weekend!

**Comment by pearcej** [comment]
@emmet0r Thanks so much for this useful contribution!

**Comment by emmet0r** [comment]
Of course! Will add the other two projects shortly ☺️
