### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by eygul** [pearcej/opensource#44]
In Section 3.3.2(sec_licensing_existing_communities.html) “Unfortunately, there are pitfalls to tho most permissive licenses when anyone can utilize the software for any purpose.” has a typo in the word "the". It is written as "tho".

**Comment by neshvig10** [comment]
fixed

**Comment by demekenega** [comment]
https://github.com/pearcej/opensource/issues/40#issuecomment-1627533649
