### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by eygul** [pearcej/opensource#45]
In Section 4.3 (sec_dev_editors.html), “code snippets - which are pre-written code blocks that can inserted into the code quickly.“ is grammatically incorrect. Instead, it should be “code snippets - which are pre-written code blocks that can be inserted into the code quickly.“ In the latter one, the word "be" is added before the word "inserted".

**Comment by demekenega** [comment]
https://github.com/pearcej/opensource/issues/40#issuecomment-1627533649
