### ISSUE TITLE
Unresponsive link 

### ISSUE THREAD

**Issue by demekenega** [pearcej/opensource#6]
1. In the acknowledgment page (acknowledgment-1.html) in the URL quiad.fedorapeople.org the first word is misspelled.

![image](https://github.com/pearcej/opensource/assets/117699634/10022d5d-ad85-4277-8887-42a8b966ea00)

**Comment by demekenega** [comment]
I believe that the URL is unnecessary because 
1. the link is incorrect.
2. the correct link is provided next to the URL.

**Comment by thaopham03** [comment]
The issue was already resolved. We are good to close the issue now.

**Comment by demekenega** [comment]
I agree. that this issue is already resolved.
