### ISSUE TITLE
Images throughout work need description or decorative attributes added for accessibility 

### ISSUE THREAD

**Issue by pearcej** [pearcej/opensource#95]
See https://pretextbook.org/doc/guide/html/overview-images.html for more details on which choice to make and how to do this.

**Comment by AnishKharel** [comment]
Fixing issue #215. This is for the area.png  in  sec_git_gettting_started.ptx.

**Comment by thaopham03** [comment]
Fixing issue #212. This is for the image distributed.png in sec_git_getting_start.ptx

**Comment by solijonovam** [comment]
fixing issue #216. This is for git-advance-testing.png in section 4.4.7.

**Comment by michelmonc** [comment]
fixing issue #217. This is for git-advance-testing.png" in the Git Branching Chapter 4.4

**Comment by stevensonmichel** [comment]
Fixing issue #217. This is for "git-head-to-testing.png" in the Git Branching Chapter 4.4.5

**Comment by tapiae1** [comment]
Fixing issue #220. This is for "git-advance-master.png" in figure 4.4.9.

**Comment by Samvae** [comment]
Fixing #222. This is for "git-two-branches.png" in figure 4.4.3

**Comment by njounkengdaizem** [comment]
Fixing issue #224. This is for "git-checkout-master.png" in figure 4.4.8 in section 4.4 Git Branching

**Comment by michelmonc** [comment]
Fixing issue #201. Two asterisk symbols, In section 5.3 Git Basics

**Comment by UlisesH09** [comment]
Fixing issue #230. This is to Add git config --global user information for first time set-up to git cheatsheet, in the Appendices section.

**Comment by IsaacSGray** [comment]
I am on it. File name is sec_oss_contributor_mountain.ptx

**Comment by eygul** [comment]
Fixing #242 . This is for "git-branch-and-history.png" in figure 4.4.3 in section 4.4 Git Branching.

**Comment by fairsilas** [comment]
Fixing issue #244 "Fix fig_tikz.ptx image description to be more descriptive"

**Comment by harpera3** [comment]
Fixing issue #267 This is for image day-times-on-globe.png in sec_community_global.ptx. located at figure 2.1.1.
